version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      POSTGRES_DB: dagster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster-web:
    image: dagster/dagster-webserver:latest
    restart: always
    environment:
      DAGSTER_HOME: /dagster
    volumes:
      - ./dagster.yaml:/dagster/dagster.yaml
      - ./workspace.yaml:/dagster/workspace.yaml
    ports:
      - "3000:3000"
    depends_on:
      - dagster-daemon
      - postgres

  dagster-daemon:
    image: dagster/dagster-daemon:latest
    restart: always
    environment:
      DAGSTER_HOME: /dagster
    volumes:
      - ./dagster.yaml:/dagster/dagster.yaml
      - ./workspace.yaml:/dagster/workspace.yaml
    depends_on:
      - postgres

volumes:
  postgres_data:
