services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      POSTGRES_DB: dagster
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dagster"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster:
    build: .
    restart: always
    environment:
      DAGSTER_HOME: /code
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "3000:3000"
    entrypoint: ["dagster", "dev", "-w", "-h", "0.0.0.0", "-p", "3000", "/code/workspace.yaml"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
