[tool.poetry]
name = "hca_orchestration"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
dagster = "^0.10.5"
google-cloud-bigquery = "^2.4.0"
google-cloud-storage = "^1.3.5"
dagster-k8s = "^0.10.5"
data-repo-client = "^1.0.194.post5"
argo-workflows = "^5.0.0"

[tool.poetry.dev-dependencies]
pdbpp = "^0.10.2"
pytest = "^6.2.1"
dagit = "^0.10.5"

[tool.poetry.scripts]
checks = "hca_utils.main:run"

[build-system]
requires = ["poetry-core=^1.1.5"]
build-backend = "poetry.core.masonry.api"
