resources:
  hca_project_copying_config:
    config:
      source_bigquery_project_id: tdr-prd1-87360b54
      source_snapshot_name: hca_prod_20201120_dcp2___20210812_dcp8
  load_tag:
    config:
      append_run_id: true
      load_tag_prefix: project_copy
  scratch_config:
    config:
      scratch_bq_project: NA
      scratch_bucket_name: broad-dsp-monster-hca-dev-temp-storage
      scratch_dataset_prefix: NA
      scratch_table_expiration_ms: 0
  target_hca_dataset:
    config:
      billing_profile_id: 390e7a85-d47f-4531-b612-165fc977d3bd
      dataset_id: 38d2d4aa-6fac-4ea1-b430-a225d0377846
      dataset_name: hca_dev_20210817_arhtesting
      project_id: datarepo-dev-2dfd8993

