resources:
  hca_project_copying_config:
    config:
      source_bigquery_project_id: tdr-prd1-87360b54
      source_snapshot_name: hca_prod_20201120_dcp2___20210812_dcp8
  load_tag:
    config:
      append_timestamp: true
      load_tag_prefix: project_copy
  scratch_config:
    config:
      scratch_bq_project: NA
      scratch_bucket_name: broad-dsp-monster-hca-dev-temp-storage
      scratch_dataset_prefix: NA
      scratch_table_expiration_ms: 0
  target_hca_dataset:
    config:
      env: "dev"
