resources:
  load_tag:
    config:
      append_run_id: true
  scratch_config:
    config:
      scratch_bq_project: broad-dsp-monster-hca-dev
      scratch_bucket_name: broad-dsp-monster-hca-dev-staging-storage
      scratch_table_expiration_ms: 86400000
  target_hca_dataset:
    config:
      env: "dev"
      policy_members: ["monster@firecloud.org"]
      billing_profile_id: 390e7a85-d47f-4531-b612-165fc977d3bd
      region: US
      qualifier: dcp2
      atlas: hca
  hca_project_id:
    config: {}
solids:
  pre_process_metadata:
    config:
      input_prefix:
