apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: import-hca-no-files
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: data-repo-name
        {{- $dataRepoName := "{{workflow.parameters.data-repo-name}}" }}
      - name: data-repo-name
        {{- $dataRepoUrl := "{{workflow.parameters.data-repo-url}}" }}
      - name: data-repo-billing-profile-id
        {{- $dataRepoBillingProfileId := "{{workflow.parameters.data-repo-billing-profile-id}}" }}
      - name: dataset-id
        {{- $datasetId := "{{workflow.parameters.dataset-id}}" }}
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    - name: main
      inputs:
        parameters:
          - name: source-bucket-name
          {{- $inputBucket := "{{inputs.parameters.source-bucket-name}}" }}
          - name: source-bucket-prefix
          {{- $inputPrefix := "{{inputs.parameters.source-bucket-prefix}}" }}
          - name: staging-bucket-prefix
          {{- $stagingPrefix := "{{inputs.parameters.staging-bucket-prefix}}" }}
      # Limit the number of active processing "arms" at a time.
      # There may be multiple pods running within each arm.
      parallelism: {{ .Values.parallelism }}
      dag:
        tasks:
          - name: stage-hca
            templateRef:
              name: stage-data
              template: main
            arguments:
              parameters:
                - name: source-bucket-name
                  value: {{ $inputBucket | quote }}
                - name: source-bucket-prefix
                  value: {{ $inputPrefix | quote }}
                - name: staging-bucket-prefix
                  value: {{ $stagingPrefix | quote }}

          - name: load-hca-no-files
            dependencies: [stage-hca]
            templateRef:
              name: load-hca-no-files
              template: main
            arguments:
              parameters:
                - name: data-repo-name
                  value: {{ $dataRepoName | quote }}
                - name: dataset-id
                  value: {{ $datasetId | quote }}
                - name: staging-bucket-prefix
                  value: {{ $stagingPrefix | quote }}
                - name: data-repo-url
                  value: {{ $dataRepoUrl | quote }}
                - name: data-repo-billing-profile-id
                  value: {{ $dataRepoBillingProfileId | quote }}
