{{- with .Values.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .k8sName }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .googleName | quote }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ printf "%s-psp" .k8sName }}
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
---
# Permissions needed by a k8s SA to run the ClinVar workflow.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .k8sName }}-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['{{ printf "%s-psp" .k8sName }}']
- apiGroups: ['']
  resources: ['pods']
  verbs: ['get', 'watch', 'patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .k8sName }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .k8sName }}
roleRef:
  kind: Role
  name: {{ .k8sName }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
