resources:
  load_tag:
    config:
      append_run_id: true
      load_tag_prefix: dev_import
  scratch_config:
    config:
      scratch_bq_project: broad-dsp-monster-hca-dev
      scratch_bucket_name: broad-dsp-monster-hca-dev-staging-storage-uc1
      scratch_dataset_prefix: dev_import
      scratch_table_expiration_ms: 86400000
  target_hca_dataset:
    config:
      dataset_id:
solids:
  pre_process_metadata:
    config:
      input_prefix:

