resources:
  hca_project_copying_config:
    config:
      source_bigquery_project_id: broad-datarepo-terra-prod-hca2
      source_snapshot_name: hca_prod_20201118_dcp1___20201209
      source_bigquery_region: US
  load_tag:
    config:
      append_run_id: true
      load_tag_prefix: prod_migration
  scratch_config:
    config:
      scratch_bq_project: NA
      scratch_bucket_name: broad-dsp-monster-prod-migration-temp-uc1
      scratch_dataset_prefix: NA
      scratch_table_expiration_ms: 0
  target_hca_dataset:
    config:
      env: "real_prod"
      policy_members: ["monster@firecloud.org"]
      billing_profile_id: 87bfdaf8-9216-4795-90c9-7ae5e7946871
      region: US
      qualifier: dcp1
solids:
  ingest_data_files:
    config:
      direct_copy_from_tdr: True
