resources:
  snapshot_config:
    config:
      managed_access: false
      dataset_qualifier: dcp2
      atlas: hca
solids:
  add_steward:
    config:
      snapshot_steward: monster-dev@dev.test.firecloud.org
