resources:
  load_tag:
    config:
      append_run_id: true
  scratch_config:
    config:
      scratch_bq_project: mystical-slate-284720
      scratch_bucket_name: broad-dsp-monster-hca-prod-staging-storage
      scratch_table_expiration_ms: 86400000
  target_hca_dataset:
    config:
      dataset_id: d30e68f8-c826-4639-88f3-ae35f00d4185
solids:
  pre_process_metadata:
    config:
      input_prefix:
