---
global:
  image:
    tag: v1.8.4
repoServer:
  serviceAccount:
    create: true
    name: hca-argocd-repo-server
  rbac:
    - apiGroups:
        - argoproj.io
      resources:
        - applications
      verbs:
        - get
        - list
        - watch
  volumes:
    - name: custom-tools
      emptyDir: {}
  initContainers:
    - name: download-tools
      image: alpine:3.8
      command: [sh, -c]
      args:
        - wget -qO /custom-tools/argo-cd-helmfile.sh https://raw.githubusercontent.com/travisghansen/argo-cd-helmfile/master/src/argo-cd-helmfile.sh &&
          chmod +x /custom-tools/argo-cd-helmfile.sh &&
          wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.98.2/helmfile_linux_amd64 &&
          chmod +x /custom-tools/helmfile
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumeMounts:
    - mountPath: /usr/local/bin/argo-cd-helmfile.sh
      name: custom-tools
      subPath: argo-cd-helmfile.sh
    - mountPath: /usr/local/bin/helmfile
      name: custom-tools
      subPath: helmfile
redis:
  enabled: false
redis-ha:
  enabled: true
  serviceAccount:
    create: true
    name: redis-sa
server:
  extraArgs:
    - --disable-auth
    - --insecure
