---
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: monster
    url: https://broadinstitute.github.io/monster-helm
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

# helm releases to be deployed
releases:
  - name: argocd-psp    # release name
    namespace: argocd   # target namespace
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: argocd-dex-server
  - name: argocd-application-controller    # release name
    namespace: argocd   # target namespace
    createNamespace: true
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: hca-argocd-application-controller
  - name: argocd-server   # release name
    namespace: argocd   # target namespace
    createNamespace: true
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: argocd-server
  - name: argocd-dex-server   # release name
    namespace: argocd   # target namespace
    createNamespace: true
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: argocd-dex-server
  - name: argocd-repo-server   # release name
    namespace: argocd   # target namespace
    createNamespace: true
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: hca-argocd-repo-server
  - name: redis-sa-haproxy   # release name
    namespace: argocd   # target namespace
    createNamespace: true
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: redis-sa-haproxy
  - name: redis-sa   # release name
    namespace: argocd   # target namespace
    createNamespace: true
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: hca-redis-sa
  - name: hca-dev   # release name
    namespace: argocd   # target namespace
    createNamespace: true
    chart: argo/argo-cd   # chart name
    missingFileHandler: Warn
    values:
      - argocd.yaml