name: PR Validation
on:
  pull_request:
    branches:
      - main
jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.DEV_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_TEST_KEY }}
          export_default_credentials: true
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@20.0.0
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Compile
        run: sbt Compile/compile Test/compile IntegrationTest/compile
      - name: Test
        run: sbt "set ThisBuild/coverageEnabled := true" test IntegrationTest/test coverageAggregate
      - name: Publish coverage
        uses: codecov/codecov-action@v1
