resources:
  load_tag:
    config:
      append_timestamp: true
      load_tag_prefix: arh
  scratch_config:
    config:
      scratch_bq_project: broad-dsp-monster-hca-dev
      scratch_bucket_name: broad-dsp-monster-hca-dev-staging-storage
      scratch_dataset_prefix: arh
      scratch_prefix_name: arh
      scratch_table_expiration_ms: 86400000
  target_hca_dataset:
    config:
      billing_profile_id: 390e7a85-d47f-4531-b612-165fc977d3bd
      dataset_id: 6f11e9ba-4548-4835-8c23-a6d2f844b774
      dataset_name: hca_monster_testing_dagster_20210628
      project_id: broad-jade-dev-data
solids:
  pre_process_metadata:
    config:
      input_prefix: gs://broad-dsp-monster-hca-dev-test-storage/mock_controlled_access/4298b4de-92f3-4cbb-bbfe-5bc11b8c2422
