resources:
  snapshot_config:
    config:
      managed_access: false
      source_hca_project_id: ''
solids:
  add_steward:
    config:
      snapshot_steward: monster@firecloud.org
  submit_snapshot_job:
    config:
      billing_profile_id: ''
