---
repositories:
  - name: dagster
    url: https://dagster-io.github.io/helm
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

# helm releases to be deployed
releases:
  # sets up a pod security policy for the given service account
  # (required by our org's broader security policy)
  - name: monster-psp    # release name
    namespace: dagster   # target namespace
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: monster-dagster
  - name: monster    # release name
    namespace: dagster   # target namespace
    chart: dagster/dagster   # chart name
    missingFileHandler: Warn
    values:
      - environment/{{ requiredEnv "ENV" }}.yaml
      - rbacEnabled: true
      - postgresql:
          serviceAccount:
            enabled: true
            name: monster-dagster
      - userDeployments:
          # "user code" we deploy to dagster; these are dagster repositories of pipelines
          enabled: true
          deployments:
            # if you add a new deployment here, make sure it's also reflected in the env files (environment/*.yaml)
            # so that env vars get propagated to it correctly
            - name: "monster-hca-ingest"
              image:
                repository: "us.gcr.io/broad-dsp-gcr-public/monster-hca-dagster"
                tag: {{ requiredEnv "GIT_SHORTHASH" }}
                pullPolicy: Always
              dagsterApiGrpcArgs:
                - "-f"
                - "/hca_orchestration/pipelines.py"
              port: 3030


