---
repositories:
  - name: dagster
    url: https://dagster-io.github.io/helm
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

# helm releases to be deployed
releases:
  # sets up a pod security policy for the given service account
  # (required by our org's broader security policy)
  - name: monster-psp    # release name
    namespace: dagster   # target namespace
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: monster-dagster
  - name: monster    # release name
    namespace: dagster   # target namespace
    chart: dagster/dagster   # chart name
    missingFileHandler: Warn
    values:
      - rbacEnabled: true
      - postgresql:
          serviceAccount:
            enabled: true
            name: monster-dagster
      - dagit:
          envConfigMaps:
            - name: hca-dagster-{{ env "ENV" }}-config
      - userDeployments:
          # "user code" we deploy to dagster; these are dagster repositories of pipelines
          enabled: true
          deployments:
            - name: "monster-hca-ingest"
              image:
                repository: "us.gcr.io/broad-dsp-gcr-public/monster-hca-dagster"
                tag: {{ env "GIT_SHORTHASH" }}
                pullPolicy: Always
              dagsterApiGrpcArgs:
                - "-f"
                - "/hca_orchestration/pipelines.py"
              port: 3030
              envConfigMaps:
                - name: hca-dagster-{{ env "ENV" }}-config
      - runLauncher:
          config:
            # k8s run launcher is the default, we'll need to change this bit if we switch to a
            # different run launcher
            k8sRunLauncher:
              envConfigMaps:
                - name: hca-dagster-{{ env "ENV" }}-config
      - dagsterDaemon:
          envConfigMaps:
            - name: hca-dagster-{{ env "ENV" }}-config


