---
repositories:
  - name: dagster
    url: https://dagster-io.github.io/helm
  - name: datarepo-helm
    url: https://broadinstitute.github.io/datarepo-helm

# helm releases to be deployed
releases:
  # sets up a pod security policy for the given service account
  # (required by our org's broader security policy)
  - name: monster-psp    # release name
    namespace: dagster   # target namespace
    chart: datarepo-helm/serviceaccount-psp   # chart name
    missingFileHandler: Warn
    values:
      - serviceAccount:
          name: monster-dagster
  - name: monster-secrets
    namespace: dagster
    chart: datarepo-helm/create-secret-manager-secret
    missingFileHandler: Warn
    values:
      - secretName: monster-dagster-secrets
        vals:
          - kubeSecretKey: SLACK_TOKEN
            path: secret/dsde/monster/{{ requiredEnv "ENV" }}/ingest/hca/dagster
            vaultKey: slack-token
  - name: monster    # release name
    namespace: dagster   # target namespace
    chart: dagster/dagster   # chart name
    missingFileHandler: Warn
    values:
      - environment/{{ requiredEnv "ENV" }}.yaml
      - rbacEnabled: true
      - postgresql:
          serviceAccount:
            enabled: true
            name: monster-dagster
      - runLauncher:
          config:
            k8sRunLauncher:
              envConfigMaps:
                # the k8s run launcher doesn't allow us to directly set a list of env vars, so we just
                # point it at the env config map the daemon generates as a workaround. this will be the
                # same set of custom env vars as every other component of the system.
                - name: monster-dagster-daemon-env
      - dagit:
        envSecrets:
          - name: monster-dagster-secrets
      - userDeployments:
          # "user code" we deploy to dagster; these are dagster repositories of pipelines
          enabled: true
          deployments:
            - name: "monster-hca-ingest"
              image:
                repository: "us.gcr.io/broad-dsp-gcr-public/monster-hca-dagster"
                tag: {{ requiredEnv "GIT_SHORTHASH" | quote }}
                pullPolicy: Always
              dagsterApiGrpcArgs:
                - "-f"
                - "/hca_orchestration/repositories.py"
              port: 3030
              envConfigMaps:
                # we can't use values.yaml to insert env vars into deployments, since overwriting lists
                # doesn't work in helmfiles. instead, like above, we just tell it to use the daemon's config map.
                - name: monster-dagster-daemon-env
              envSecrets:
                - name: monster-dagster-secrets
