dataflow:
  region: us-central1
  workerMachineType: n1-standard-4
  autoscaling:
    minWorkers: 4
    maxWorkers: 16
  useFlexRS: false
repo:
  pollTimeout: 86400
argoTemplates:
  createBQDataset:
    create: true
    name: create-dataset
  exportBQTable:
    create: true
    name: export-table
  ingestTable:
    create: true
    name: ingest-table
  softDeleteTable:
    create: true
    name: soft-delete-table
parallelism: 8
