dataflow:
  region: us-central1
  workerMachineType: n1-standard-1
  autoscaling:
    minWorkers: 4
    maxWorkers: 8
  useFlexRS: false
repo:
  pollTimeout: 86400
argoTemplates:
  createBQDataset:
    create: true
    name: create-dataset
  exportBQTable:
    create: true
    name: export-table
  diffBQTable:
    create: true
    name: diff-bq-table
    schemaImageName: us.gcr.io/broad-dsp-gcr-public/hca-schema
  ingestTable:
    create: true
    name: ingest-table
  softDeleteTable:
    create: true
    name: soft-delete-table
parallelism: 4
