name: Tag Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-**
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@20.0.0
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          project_id: broad-dsp-monster-dev
          service_account_email: jenkins-gcr-pusher@broad-dsp-monster-dev.iam.gserviceaccount.com
          service_account_key: ${{ secrets.Base64ServiceAccountKey }}
          export_default_credentials: true
      - name: Setup GCR auth
        run: gcloud auth configure-docker --quiet
      - uses: azure/setup-helm@v1
        with:
          version: 'v3.1.2'
      - uses: broadinstitute/setup-chart-releaser@v1
        with:
          version: '1.0.0-beta.1'
      - name: Publish
        run: sbt publish reindexHelmRepository
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
