name: PR Validation
on:
  pull_request:
    branches:
      - master
jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.DEV_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_TEST_KEY }}
          export_default_credentials: true
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@20.0.0
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Compile
        run: sbt Compile/compile Test/compile IntegrationTest/compile
      - name: Test
        run: sbt "set ThisBuild/coverageEnabled := true" test IntegrationTest/test coverageAggregate
      - name: DataflowCheck
          env:
            GITHUB_SHA: ${{github.sha}}
          run: >
            sbt "hca-transformation-pipeline/run
                --inputPrefix=gs://broad-dsp-monster-hca-dev-test-storage/integration/ebi_small/ebi_test
                --outputPrefix=gs://broad-dsp-monster-hca-dev-temp-storage/integration/output_${GITHUB_SHA}
                --runner=direct"
      - name: Publish coverage
        uses: codecov/codecov-action@v1
