# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate Python

on:
  pull_request:
    branches:
      - master

jobs:
  python-validation:
    runs-on: ubuntu-latest
    env:
      ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1
    - name: test
      run: echo "${{ github.workspace }}/orchestration/dagster_orchestration"
    - name: Install dependencies
      run: poetry install
      working-directory: ${{ github.workspace }}/orchestration/dagster_orchestration
    - name: Run linter
      run: flake8
      working-directory: ${{ github.workspace }}/orchestration/dagster_orchestration
    - name: Run Python tests
      run: poetry run pytest
      working-directory: ${{ github.workspace }}/orchestration/dagster_orchestration
